---
- name: Install git on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
        
- name: Add several users
   ansible.builtin.user:
     name: "{{item}}"
     state: present
   loop:
     - testuser1
     - testuser2
     - sachin
     - foo
