---
# ansible -m file -a 'path=/tmp/surekha.txt state=present' all
# ansible prod -m copy -a 'src=/etc/hosts dest=/tmp'
# YAML - yet another markup lang
- name: create at new file and delete it.
  hosts: all
  tasks:
   - name: create username file in tmp directory
     file:
       path: '/tmp/surekha.txt'
       state: touch
   - name: copy ansible hosts file on every node
     copy: 
      src: '/etc/ansible/hosts'
      dest: '/tmp'
# touch hello.yml
# gedit or vi hello.yml
# :wq
# ansible-playbook hello.yml